name: kira_auth
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluid_layout: ^0.1.0
  flutter_staggered_grid_view: ^0.3.0
  google_fonts: ^1.1.0
  fluro:
    git: git://github.com/theyakka/fluro.git
  fl_chart: ^0.10.1
  date_time_format: ^1.1.1+1
  fluttertoast: ^7.1.6

  # bip39: mnemonic code for generating deterministic keys
  bip39: ^1.0.3

  # Nano core functions
  flutter_nano_ffi: ^1.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  blake_hash: ^1.0.0
  base32: ^1.1.1
  tuple: ^1.0.3
  encrypt: ^4.0.2
  path_provider: ^1.6.11
  html: ^0.14.0+3
  shared_preferences: ^0.5.10
  clipboard: ^0.1.2+8
  http: ^0.12.2
  basic_utils: ^2.6.2
  json_annotation: ^3.0.1
  pointycastle: ^1.0.2
  bip32: ^1.0.5
  bip_bech32: ^0.1.3
  bloc: ^6.0.3
  equatable: ^1.2.5
  qr_flutter: ^3.2.0
  sacco: ^0.1.4
  jdenticon_dart: ^1.2.1+1
  intl: ^0.16.1
  secp256k1: ^0.2.2
  crypto: ^2.1.5
  flutter_bloc: ^6.1.1
  ##flutter_svg: ^0.19.2+1
  # BLAKE2b and BLAKE2s cryptographic hashing functions

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  json_serializable: ^3.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/config.json
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
